const products = [
  {
    id: 1,
    name: "laptop",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "1799",
    count: 842,
    img: "./../../public/images/laptop.jpg",
  },
  {
    id: 2,
    name: "tablet",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "600",
    count: 128,
    img: "./../../public/images/tablet.jpg",
  },
  {
    id: 3,
    name: "mobile",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "1200",
    count: 102,
    img: "./../../public/images/phone.jpg",
  },
  {
    id: 4,
    name: "pc",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "5000",
    count: 55,
    img: "./../../public/images/PC.jpg",
  },
  {
    id: 5,
    name: "charger",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "25",
    count: 52335,
    img: "./../../public/images/charger.jpg",
  },
  {
    id: 6,
    name: "monitor",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "500",
    count: 55,
    img: "./../../public/images/monitor.jpg",
  },
  {
    id: 7,
    name: "power bank",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "110",
    count: 5125,
    img: "./../../public/images/powerbank.jpg",
  },
  {
    id: 8,
    name: "Headphones",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    price: "200",
    count: 552,
    img: "./../../public/images/Headphones.jpg",
  },
];
export default products;
